// AUTO-GENERATED BY onyx-gen. DO NOT EDIT.
// Generated at 2026-01-12T03:43:22.088Z

export interface Task {
  id?: string;
  title?: string;
  description?: string;
  status?: string;
  dueDate?: string;
  createdAt?: string;
  updatedAt?: string;
  [key: string]: any;
}

export type OnyxSchema = {
  Task: Task;
};

export type Schema = OnyxSchema;
export const Schema = {} as OnyxSchema;

export enum tables {
  Task = "Task",
}

